# Generated by Django 3.2.7 on 2021-11-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trim',
            field=models.ManyToManyField(to='tires.Trim'),
        ),
    ]
