# Generated by Django 3.2.7 on 2021-11-28 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
                ('width', models.PositiveIntegerField()),
                ('asepect_ratio', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'tires',
            },
        ),
        migrations.CreateModel(
            name='Trim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
                ('trim_id', models.PositiveIntegerField()),
                ('back_tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trim_back_tire', to='tires.tire')),
                ('front_tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trim_front_tire', to='tires.tire')),
            ],
            options={
                'db_table': 'trims',
            },
        ),
    ]
